 platform :ios, '12.0'

inhibit_all_warnings!

target 'DevtoolsFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DevtoolsFramework
  pod 'SwiftLint'
  pod 'Yams', '~> 4.0.6'

  target 'DevtoolsFrameworkTests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Inherit the deployment target defined in this Podfile instead, e.g. platform :ios, '11.0' at the top of this file
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
