platform :ios, '12.0'

inhibit_all_warnings!
use_frameworks!

target 'DevtoolsFramework' do
  pod 'SwiftLint', '0.46.5'
  pod 'Yams', '5.0.0'
end

target 'DevtoolsFrameworkTests' do
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Inherit the deployment target defined in this Podfile instead, e.g. platform :ios, '11.0' at the top of this file
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
