platform :ios, '12.0'

inhibit_all_warnings!
use_frameworks!

target 'DevToolsApp' do
  pod 'SwiftLint'
  # TODO Remove local paths before release
  pod 'DevtoolsFramework', :path => '../../devtools/ios' # Local path for development purposes

  target 'DevToolsAppTests' do
    inherit! :search_paths
  end

  target 'DevToolsAppUITests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Inherit the deployment target defined in this Podfile instead, e.g. platform :ios, '11.0' at the top of this file
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
