 platform :ios, '12.0'

target 'DevToolsApp' do
  use_frameworks!

  # Pods for DevToolsApp
  pod 'SwiftLint'
  # TODO Remove local paths before release
  pod 'Yams', :git => 'git@github.com:jpsim/Yams.git', :branch => 'fix-cocoapods'
  pod 'DevtoolsFramework', :path => '../../devtools/ios' # Local path for development purposes.

  target 'DevToolsAppTests' do
    inherit! :search_paths
    # Pods for testingq
  end

  target 'DevToolsAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Inherit the deployment target defined in this Podfile instead, e.g. platform :ios, '11.0' at the top of this file
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
