 platform :ios, '12.1'

target 'DevToolsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DevToolsApp
  pod 'SwiftLint'
  # TODO Remove local paths before release
  pod 'DevtoolsFramework', :path => '../../devtools/ios' # Local path for development purposes.

  target 'DevToolsAppTests' do
    inherit! :search_paths
    # Pods for testingq
  end

  target 'DevToolsAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
