name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pullreqest:
    name: "Check pull request styling"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
    steps:
      - name: "Check branch name and commit messages style"
        uses: maximbircu/pull-request-checkstyle@v1.0.0
        with:
          branch-name-regex: '\d+(-([a-z])+)+'
          commit-message-title-regex: '^[A-Z].*'

  checkstyle:
    name: "Check project styling (Android lint, Detekt and Ktlint)"
    runs-on: ubuntu-latest
    steps:
      - name: SCM
        uses: actions/checkout@v2

      - name: Android lint
        uses: vgaidarji/android-github-actions-build@v1.0.1
        with:
          args: "./gradlew lintDebug"

      - name: Detekt
        uses: vgaidarji/android-github-actions-build@v1.0.1
        with:
          args: "./gradlew detekt"

      - name: Ktlint
        uses: vgaidarji/android-github-actions-build@v1.0.1
        with:
          args: "./gradlew ktlint"

  test:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - name: SCM
        uses: actions/checkout@v2

      - name: Test
        uses: vgaidarji/android-github-actions-build@v1.0.1
        with:
          args: "./gradlew testDebugUnitTest"

      - name: JaCoCo
        uses: vgaidarji/android-github-actions-build@v1.0.1
        with:
          args: "./gradlew jacocoTestReport"

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  build:
    name: "Assemble artifacts"
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: SCM
        uses: actions/checkout@v2

      # Assemble artifacts
      - name: Assemble
        uses: vgaidarji/android-github-actions-build@v1.0.1
        with:
          args: "./gradlew assemble"
