name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  pullreqest:
    name: Check pull request styling
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
    steps:
      - name: Check branch name and commit messages style
        uses: maximbircu/pull-request-checkstyle@v1.0.0
        with:
          branch-name-regex: '\d+(-([a-z])+)+'
          commit-message-title-regex: '^[A-Z].*'

  checkstyle:
    name: Check project styling (Android lint, Detekt and Ktlint)
    runs-on: ubuntu-latest
    steps:
      - name: SCM
        uses: actions/checkout@v2

      - name: Android lint
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: lintDebug

      - name: Detekt
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: detekt

      - name: Ktlint
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: ktlint

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: SCM
        uses: actions/checkout@v2

      - name: Test
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: testDebugUnitTest

      - name: JaCoCo
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: jacocoTestReport

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  build:
    name: Assemble artifacts
    runs-on: ubuntu-latest # TODO #16 Replace with macos-latest so the iOS frameworks a build too.
    steps:
      - name: SCM
        uses: actions/checkout@v2

      - name: Assemble
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: assembleDebug

